container:
  image: cirrusci/flutter:latest

test_task:
  # pub_cache:
  #   folder: $HOME/.pub-cache
  #   fingerprint_script: cat pubspec.lock
  #   populate_script: pub get
  pub_get_script: pub get
  format_script: dartfmt **/*.dart -n --set-exit-if-changed
  analyze_script: dartanalyzer --fatal-infos .
  # publishable_script: pub publish --dry-run
  environment:
    CODECOV_TOKEN: ENCRYPTED[64bbc39e3fd05e26073199c780e33a45609d3b2cc824dc11652e0c8c6bbf14db56ed5bd50153f67cc2a89a5d5185cd9a]
  test_script:
  - dart tools/server.dart & # start websocket server
  - pub run test_coverage
  # workaround until https://github.com/cirruslabs/docker-images-flutter/pull/18
  - sudo apt-get update &&
    sudo apt-get install -y --allow-unauthenticated --no-install-recommends chromium
  - pub run test -p chromium
  - bash <(curl -s https://codecov.io/bash)
