name: flutter_example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  websocket:
    path: ../..
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
